/** Inline script: select-all + Shift-click range on checkboxes named "sel". */
export const mailsSelectScript = [
  "(function () {",
  "  var form = document.getElementById('mails-bulk');",
  "  if (!form) return;",
  "  var boxes = function () { return Array.prototype.slice.call(form.querySelectorAll('input[name=\"sel\"]')); };",
  "  var last = -1;",
  "  var all = document.getElementById('mails-all');",
  "  if (all) all.addEventListener('change', function () {",
  "    boxes().forEach(function (c) { c.checked = all.checked; });",
  "  });",
  "  form.addEventListener('click', function (e) {",
  "    var t = e.target;",
  "    if (!t || t.name !== 'sel' || t.type !== 'checkbox') return;",
  "    var list = boxes();",
  "    var i = list.indexOf(t);",
  "    if (e.shiftKey && last >= 0 && i >= 0) {",
  "      var a = Math.min(last, i), b = Math.max(last, i);",
  "      var on = t.checked;",
  "      for (var n = a; n <= b; n++) list[n].checked = on;",
  "    }",
  "    last = i;",
  "  });",
  "})();",
].join("\n");
