/** Inline script: tri-state (none → asc → desc → none) + Shift for extra columns. */
export const tableSortScript = [
  "(function () {",
  "  function textOf(td) {",
  "    return String(td && td.innerText || '').replace(/\\s+/g, ' ').trim();",
  "  }",
  "  function parseVal(raw) {",
  "    var t = raw.replace(/^[—–-]$/, '');",
  "    if (!t) return { n: null, s: '' };",
  "    var num = t.replace(/\\s/g, '').replace(',', '.');",
  "    if (/^-?\\d+(\\.\\d+)?$/.test(num)) return { n: Number(num), s: t };",
  "    if (/^\\d{4}-\\d{2}-\\d{2}/.test(t)) {",
  "      var ms = Date.parse(t);",
  "      if (!isNaN(ms)) return { n: ms, s: t };",
  "    }",
  "    return { n: null, s: t.normalize('NFD').replace(/[\\u0300-\\u036f]/g, '').toLowerCase() };",
  "  }",
  "  function cmp(a, b, dir) {",
  "    var av = a.n, bv = b.n;",
  "    if (av != null && bv != null && av !== bv) return av < bv ? -dir : dir;",
  "    if (av != null && bv == null) return -dir;",
  "    if (av == null && bv != null) return dir;",
  "    if (a.s < b.s) return -dir;",
  "    if (a.s > b.s) return dir;",
  "    return 0;",
  "  }",
  "  function paint(table, keys) {",
  "    var heads = table.tHead && table.tHead.rows[0] ? table.tHead.rows[0].cells : [];",
  "    for (var i = 0; i < heads.length; i++) {",
  "      var th = heads[i];",
  "      var k = -1;",
  "      for (var j = 0; j < keys.length; j++) if (keys[j].i === i) k = j;",
  "      th.setAttribute('aria-sort', k < 0 ? 'none' : keys[k].dir === 1 ? 'ascending' : 'descending');",
  "      var mark = th.querySelector('.sort-mark');",
  "      if (!mark) {",
  "        mark = document.createElement('span');",
  "        mark.className = 'sort-mark';",
  "        th.appendChild(mark);",
  "      }",
  "      if (k < 0) {",
  "        mark.textContent = '';",
  "      } else {",
  "        mark.textContent = (keys[k].dir === 1 ? ' \\u2191' : ' \\u2193') + (keys.length > 1 ? String(k + 1) : '');",
  "      }",
  "    }",
  "  }",
  "  function apply(table, keys) {",
  "    var tb = table.tBodies[0];",
  "    if (!tb) return;",
  "    var rows = Array.prototype.slice.call(tb.rows);",
  "    if (!keys.length) {",
  "      rows.sort(function (a, b) { return Number(a.getAttribute('data-orig')) - Number(b.getAttribute('data-orig')); });",
  "    } else {",
  "      rows.sort(function (a, b) {",
  "        for (var k = 0; k < keys.length; k++) {",
  "          var col = keys[k].i;",
  "          var d = keys[k].dir;",
  "          var c = cmp(parseVal(textOf(a.cells[col])), parseVal(textOf(b.cells[col])), d);",
  "          if (c) return c;",
  "        }",
  "        return Number(a.getAttribute('data-orig')) - Number(b.getAttribute('data-orig'));",
  "      });",
  "    }",
  "    rows.forEach(function (r) { tb.appendChild(r); });",
  "    paint(table, keys);",
  "  }",
  "  function enhance(table) {",
  "    var headRow = table.tHead && table.tHead.rows[0];",
  "    var tb = table.tBodies[0];",
  "    if (!headRow || !tb || tb.rows.length < 2) return;",
  "    var keys = [];",
  "    Array.prototype.forEach.call(tb.rows, function (r, i) { r.setAttribute('data-orig', String(i)); });",
  "    Array.prototype.forEach.call(headRow.cells, function (th, col) {",
  "      th.classList.add('sortable');",
  "      th.tabIndex = 0;",
  "      th.title = 'Clique: ordenar (asc/desc/off). Shift+clique: coluna extra.';",
  "      function cycle(multi) {",
  "        var idx = -1;",
  "        for (var j = 0; j < keys.length; j++) if (keys[j].i === col) idx = j;",
  "        if (multi) {",
  "          if (idx < 0) keys.push({ i: col, dir: 1 });",
  "          else if (keys[idx].dir === 1) keys[idx].dir = -1;",
  "          else keys.splice(idx, 1);",
  "        } else if (idx === 0 && keys.length === 1) {",
  "          if (keys[0].dir === 1) keys[0].dir = -1;",
  "          else keys = [];",
  "        } else {",
  "          keys = [{ i: col, dir: 1 }];",
  "        }",
  "        apply(table, keys);",
  "      }",
  "      th.addEventListener('click', function (e) {",
  "        if (e.target.closest && e.target.closest('a, button, input, select, label')) return;",
  "        e.preventDefault();",
  "        cycle(e.shiftKey);",
  "      });",
  "      th.addEventListener('keydown', function (e) {",
  "        if (e.key === 'Enter' || e.key === ' ') {",
  "          e.preventDefault();",
  "          cycle(e.shiftKey);",
  "        }",
  "      });",
  "    });",
  "    paint(table, keys);",
  "  }",
  "  document.querySelectorAll('table').forEach(enhance);",
  "})();",
].join("\n");
