import { getDb } from "../db.js";
import { insertMailRule, insertWaWatch, type MailRule } from "./store.js";
import { upsertAllow } from "../whatsapp/store.js";

export type MailRuleInput = Omit<MailRule, "id">;

/** Carga inicial única. Não lê Claude. Não volta a correr se já houver regras. */
export const INITIAL_MAIL_RULES: MailRuleInput[] = [
    {
      name: "Não mover helpdesk",
      kind: "keep",
      accountId: "*",
      matchFrom: "helpdesk@bwb.pt",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 0,
      enabled: true,
    },
    {
      name: "Não mover pCloud (segurança/conta)",
      kind: "keep",
      accountId: "*",
      matchFrom: "team@pcloud.com",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 0,
      enabled: true,
    },
    {
      name: "Não mover facturas/recibos",
      kind: "keep",
      accountId: "*",
      matchFrom: "",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: true,
      catchSecurity: false,
      purgeAfterDays: 0,
      enabled: true,
    },
    {
      name: "Não mover alertas de segurança",
      kind: "keep",
      accountId: "*",
      matchFrom: "",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: true,
      purgeAfterDays: 0,
      enabled: true,
    },
    {
      name: "Helpdesk BWB (arquivo por cliente)",
      kind: "helpdesk",
      accountId: "*",
      matchFrom: "helpdesk@bwb.pt",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "helpdesk",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 0,
      enabled: true,
    },
    {
      name: "AlphaSignal",
      kind: "newsletters",
      accountId: "*",
      matchFrom: "news@alphasignal.ai",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "newsletters",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "Supabase — só Supa Update",
      kind: "newsletters",
      accountId: "*",
      matchFrom: "welcome@supabase.com",
      matchSubject: "",
      subjectPrefix: "Supa Update",
      fromDomain: "",
      destFolder: "newsletters",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "Odoo — notificações / boletins",
      kind: "newsletters",
      accountId: "*",
      matchFrom: "",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "odoo.com",
      destFolder: "newsletters",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: true,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "LinkedIn — notificações",
      kind: "newsletters",
      accountId: "*",
      matchFrom: "",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "linkedin.com",
      destFolder: "newsletters",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "BCN — cartão / preçário / dados",
      kind: "newsletters",
      accountId: "*",
      matchFrom: "",
      matchSubject: "cartão|preçário|atualize os seus dados",
      subjectPrefix: "",
      fromDomain: "banco",
      destFolder: "newsletters",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "Realmac / RapidWeaver",
      kind: "marketing",
      accountId: "*",
      matchFrom: "support@realmacsoftware.com",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "marketing",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "Dealnotes / SuperCool",
      kind: "marketing",
      accountId: "*",
      matchFrom: "broadcast@dealnotes.ai",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "marketing",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "pCloud promo (pcloud.email)",
      kind: "marketing",
      accountId: "*",
      matchFrom: "team@pcloud.email",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "marketing",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "PayPal marketing",
      kind: "marketing",
      accountId: "*",
      matchFrom: "noreply@news.paypal.com",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "marketing",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "SMTP2GO",
      kind: "marketing",
      accountId: "*",
      matchFrom: "emily@smtp2go.com",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "marketing",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "Sent Team",
      kind: "marketing",
      accountId: "*",
      matchFrom: "team@sent.dm",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "marketing",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "Microsoft Rewards",
      kind: "marketing",
      accountId: "*",
      matchFrom: "microsoft",
      matchSubject: "reward|ponto|points|earn",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "marketing",
      splitPromo: false,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "Endesa — só promoções",
      kind: "marketing",
      accountId: "*",
      matchFrom: "endesa",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "marketing",
      splitPromo: true,
      catchPromo: false,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "Texto promocional (resto)",
      kind: "marketing",
      accountId: "*",
      matchFrom: "",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "marketing",
      splitPromo: false,
      catchPromo: true,
      catchDigest: false,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
    {
      name: "Digest / newsletter genérico",
      kind: "newsletters",
      accountId: "*",
      matchFrom: "",
      matchSubject: "",
      subjectPrefix: "",
      fromDomain: "",
      destFolder: "newsletters",
      splitPromo: false,
      catchPromo: false,
      catchDigest: true,
      odooNotifications: false,
      catchInvoice: false,
      catchSecurity: false,
      purgeAfterDays: 8,
      enabled: true,
    },
];

export function seedRulesAsMailRules(): MailRule[] {
  return INITIAL_MAIL_RULES.map((r, i) => ({ ...r, id: i + 1 }));
}

export function seedInitialIfEmpty(): void {
  const db = getDb();
  const rules = db.prepare("SELECT COUNT(*) AS c FROM mail_rules").get() as { c: number };
  if (rules.c === 0) {
    for (const row of INITIAL_MAIL_RULES) insertMailRule(row);
  }

  const schedules = db.prepare("SELECT COUNT(*) AS c FROM schedules").get() as { c: number };
  if (schedules.c === 0) {
    db.prepare(
      `INSERT OR IGNORE INTO schedules (id, title, job, hour, weekdays_only, enabled)
       VALUES (?,?,?,?,?,1)`
    ).run("triage", "Organizar INBOX", "triage", 7, 1);
    db.prepare(
      `INSERT OR IGNORE INTO schedules (id, title, job, hour, weekdays_only, enabled)
       VALUES (?,?,?,?,?,1)`
    ).run("agt-kb", "Base de conhecimento AGT", "agt-kb", 12, 0);
  }

  const watches = db.prepare("SELECT COUNT(*) AS c FROM wa_watches").get() as { c: number };
  if (watches.c === 0) {
    const id = insertWaWatch({
      name: "AGT - IVA ANGOLA",
      keywords: "faturação eletrónica, SAFT-AO, certificação, IVA",
      kbEnabled: true,
      enabled: true,
      chats: [
        {
          accountId: "a",
          chatJid: "244928277927-1565965350@g.us",
          label: "AGT - IVA ANGOLA",
        },
      ],
    });
    void id;
    upsertAllow("a", "244928277927-1565965350@g.us", "AGT - IVA ANGOLA");
  }
}
